// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neddit.Model;

#nullable disable

namespace Neddit.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Neddit.Model.Comment", b =>
                {
                    b.Property<float>("commentId")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("threadId")
                        .HasColumnType("REAL");

                    b.Property<float>("userId")
                        .HasColumnType("REAL");

                    b.Property<int>("votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("commentId");

                    b.HasIndex("threadId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Neddit.Model.Thread", b =>
                {
                    b.Property<float>("threadId")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("userId")
                        .HasColumnType("REAL");

                    b.Property<int>("votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("threadId");

                    b.ToTable("Threads", (string)null);
                });

            modelBuilder.Entity("Neddit.Model.User", b =>
                {
                    b.Property<float>("userId")
                        .HasColumnType("REAL");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Neddit.Model.Comment", b =>
                {
                    b.HasOne("Neddit.Model.Thread", null)
                        .WithMany("comments")
                        .HasForeignKey("threadId");
                });

            modelBuilder.Entity("Neddit.Model.Thread", b =>
                {
                    b.Navigation("comments");
                });
#pragma warning restore 612, 618
        }
    }
}
